name: CMake

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu",
            os: ubuntu-latest,
            build_type: RelWithDebInfo,
            gtk_tsm: "On"
          }
        - {
            name: "macOS",
            os: macos-latest,
            build_type: RelWithDebInfo,
            gtk_tsm: "Off"
          }

    steps:
    - uses: actions/checkout@v2

    - name: Print env
      run: |
        echo github.event.action: ${{ github.event.action }}
        echo github.event_name: ${{ github.event_name }}

    - name: Install dependencies on Ubuntu
      if: startsWith(matrix.config.name, 'Ubuntu')
      run: sudo apt-get install -y check valgrind libgtk-3-dev libpango1.0-dev pkg-config

    - name: Install dependencies on macOS
      if: startsWith(matrix.config.name, 'macOS')
      run: brew install check

    - name: Configure CMake on Ubuntu
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DBUILD_TESTING=On -DBUILD_GTKTSM=${{ matrix.config.gtk_tsm }}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ./build --config ${{ matrix.config.build_type }}

    - name: Test
      working-directory: ./build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{ matrix.config.build_type }}

